dist: xenial
language: php
matrix:
  include:
  - php: 7.2
    env: EXECUTE_DEPLOYMENT=true
  - php: 7.3
    env: deps=low UPDATE_TOOLS=true
  - php: 7.4
  fast_finish: true
cache:
  directories:
  - $HOME/.composer/cache
  - build/tools/.composer/cache
before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
- phpenv config-rm xdebug.ini || echo "XDebug is not enabled"
- export TOOLBOX_VERSION=$(echo ${TRAVIS_TAG:-"dev"} | sed -e 's/^v//')
- git config user.email 'jakub@zalas.pl' && git config user.name 'Jakub Zalas'
install:
- if [[ $deps = low ]]; then make update-min; else make install; fi
script:
- if [[ $deps = low ]]; then make test-min; else make test; fi
- make package package-devkit test-integration
after_success:
- test "$TRAVIS_PULL_REQUEST" == "false" && test "$EXECUTE_DEPLOYMENT" == "true" && make website publish-website
- test "$TRAVIS_EVENT_TYPE" == "cron" && test "$UPDATE_TOOLS" == "true" && GITHUB_TOKEN=$GH_TOKEN make update-phars
deploy:
  provider: releases
  api_key:
    secure: Ds7ye+pqAJsOOR+Bta0DtrJAOKEpHqNJEkdHSAZAE3Nc3IUXneE4kpSvOzzYtzcFqz7GCduK3kFy0JNNI9tuSQ5X0EvjUk17wIqZzoRAGaiGjsBoqG+DqCOnzqiEHehfqr/rMHQYsIYIdAXz3YgFoVYpRx0mhitnwUQN4qIs350kKyN53vfmrPmOKyrIjNRtJgTD7MGdadUYgXwVDdEsO9efltg3uTRLsugZ7iYc8f4v/olTP4FO1Hryi69lATz3NXK3T6ylQEJFklMF9Q5Twu/obhBnxQ4izoeuXcK5hL8wqyWn0jQyCh1wh+lIcH0Lc4/A2ZNoCAuVF13cc2WnC6rOcyqeopFkU7eISUCvuT+UbG8OX7I2YJGwNA788UDi61Emt3yoo7o7Woqg0n29+PVItFUxR0vLhVyakqnIAbn/HPI6ezGsrTIlzwz551iszJBfagsRZZ2GOpcNqpfbhXP+qiXa3WtLCiTQIo7oOryl/lCxjAswbKf8/7J8EJjfMNdUJS2h1IuZCINkUh7+C+wAM5nFanM86fRQjeU4OF4MbGGQyWTj7wSnUucff0olLzafRha6UUVE3YbU65L3AoafF/pBHbnj/z7kn/UREctSfo2nk3ubfs0T4Q+kGJMYYcTCYwrqJMCRN3/iGTNgelrGJGLcjAUJNqp5fHcIKy4=
  file:
  - build/toolbox.phar
  - build/devkit.phar
  skip_cleanup: true
  on:
    tags: true
    repo: jakzal/toolbox
    condition: "$EXECUTE_DEPLOYMENT"
env:
  global:
    secure: "kIsYjPUzSaCVII5DGE3zNi88fg+L3PMANyMZnrYom+zym5HwAVVzwM/dnsP+XFiqkeuuAqttNolR2D4XyY172F+jfpL3YVEC2P/zGRK2TlHu2TXCqsYx8V/bSPFCmBoWvZrx6qsuocrASaN3EmtZUg4jOnfanYBvEnw+pkLOCzJONaz0xgZVxogpUS+fk2wgXI2vHdHCEZxGcz5YIiyS/v8gWP5iUL6+CADlY9ES+DBSbaz8pP82oSQ8OZmGKRD14dK2dzMksy9MdRyfIHtTvIdo8dqchTjRh6TeXTSc+Xz6LnyQiWJOOBgnVwScILPiYze+ElW5x68fNiyVcbfSuT67fePDEGv8pCO0m0YqctsLrlCuasCx91CgPID3regyXDXeb6Xiz66/+ZzsK0QYCkUzmlkWSHlWASjrDf1703oPQIzXxx5+69ksXLmX+KmPSLsKjsirmfAaCZDPVrsxPxEjUN2Sr6anvL8BWcV36v0h29ingi3dhIBfg4wgJqBG/axiZiK63WfKqwFyFBN7F/lxrdCJZgzVOyCdjDBdcXdTNjESvUC9A3nPJR8keZ3oMlUS4kCVyFpWgB0eBF88TS8aUnWKELXndmGxvQh9NQEW4dj1FjtMHi1ZgLUosixKx7d1MBDBBp9Vg2qYCMbs3g/d6rO8is4aFR8Uc9DjUpY="
addons:
  snaps:
  - name: hub
    confinement: classic
